# url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
url: https://annetarvus.github.io
# baseurl: ""
title: "Anne Tarvus" # the name of your site, e.g. ACME Corp.
google_analytics: G-QDDNCX8B7L